// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://flaq.club/privacy-policy",
        "contact": {
            "name": "Ashwin Prasad",
            "url": "http://www.swagger.io/support",
            "email": "ashwin@flaq.club"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Enter login details",
                        "name": "LoginBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User signup",
                "parameters": [
                    {
                        "description": "Add Data",
                        "name": "SignupBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignupBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/auth/token/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Issue a new Access token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "RefreshTokenBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RefreshTokenBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/campaign/": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Campaigns"
                ],
                "summary": "Get all campaigns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/campaign/a": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Campaign Admin"
                ],
                "summary": "Create a campaign",
                "parameters": [
                    {
                        "description": "Campaign Details",
                        "name": "models.Campaign",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Campaign"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/campaign/a/quiz/add": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Campaign Admin"
                ],
                "summary": "Create a quiz template [FOR ADMIN]",
                "parameters": [
                    {
                        "description": "Quiz and Campaign Details",
                        "name": "addQuizToCampaignBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/campaigns.addQuizToCampaignBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/campaign/a/quiz/template": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Campaign Admin"
                ],
                "summary": "Create a quiz template",
                "parameters": [
                    {
                        "description": "Campaign Details",
                        "name": "models.QuizTemplate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.QuizTemplate"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/campaign/participate": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Campaigns"
                ],
                "summary": "Create a campaign",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Campaign ID",
                        "name": "campaignParticipationBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/campaigns.campaignParticipationBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/campaign/{id}/quiz": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Campaigns"
                ],
                "summary": "Get all campaigns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Campaign ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/payments": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Register a new UPI Payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/payments/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Payments"
                ],
                "summary": "Register a new UPI Payment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Register Payment",
                        "name": "registerPaymentBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/payments.registerPaymentBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/users/apply-referral": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Apply a referral code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Add Referral Data",
                        "name": "ApplyReferralBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/users.ApplyReferralBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/users/profile": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "auth.LoginBody": {
            "type": "object",
            "required": [
                "Email",
                "Password"
            ],
            "properties": {
                "Email": {
                    "type": "string"
                },
                "Password": {
                    "type": "string"
                }
            }
        },
        "auth.RefreshTokenBody": {
            "type": "object",
            "required": [
                "RefreshToken"
            ],
            "properties": {
                "RefreshToken": {
                    "type": "string"
                }
            }
        },
        "auth.SignupBody": {
            "type": "object",
            "required": [
                "Email",
                "Password"
            ],
            "properties": {
                "Email": {
                    "type": "string"
                },
                "Password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 6
                }
            }
        },
        "campaigns.addQuizToCampaignBody": {
            "type": "object",
            "properties": {
                "CampaignId": {
                    "type": "string"
                },
                "QuizTemplateId": {
                    "type": "string"
                }
            }
        },
        "campaigns.campaignParticipationBody": {
            "type": "object",
            "properties": {
                "CampaignId": {
                    "type": "string"
                }
            }
        },
        "models.Campaign": {
            "type": "object",
            "required": [
                "CurrentAirdrop",
                "Description",
                "Name",
                "RequiredFlaq",
                "TickerName",
                "TotalAirdrop"
            ],
            "properties": {
                "ArticleUrls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "CurrentAirdrop": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "Id": {
                    "type": "string"
                },
                "Name": {
                    "type": "string"
                },
                "QuizIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "Quizzes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.QuizTemplate"
                    }
                },
                "RequiredFlaq": {
                    "type": "integer"
                },
                "TaskType": {
                    "type": "string"
                },
                "TickerName": {
                    "type": "string"
                },
                "TotalAirdrop": {
                    "type": "integer"
                },
                "YTVideoUrl": {
                    "type": "string"
                }
            }
        },
        "models.Question": {
            "type": "object",
            "required": [
                "AnswerIndex",
                "Description",
                "Options",
                "Question"
            ],
            "properties": {
                "AnswerIndex": {
                    "type": "integer"
                },
                "Description": {
                    "type": "string"
                },
                "Options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "Question": {
                    "type": "string"
                }
            }
        },
        "models.QuizTemplate": {
            "type": "object",
            "required": [
                "Questions",
                "Title"
            ],
            "properties": {
                "Questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Question"
                    }
                },
                "Title": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "payments.registerPaymentBody": {
            "type": "object",
            "required": [
                "Amount"
            ],
            "properties": {
                "Amount": {
                    "type": "string"
                }
            }
        },
        "users.ApplyReferralBody": {
            "type": "object",
            "required": [
                "ReferralCode"
            ],
            "properties": {
                "ReferralCode": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Flaq API",
	Description:      "This is a sample server server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
