basePath: /
definitions:
  auth.LoginBody:
    properties:
      Email:
        type: string
      Password:
        type: string
    required:
    - Email
    - Password
    type: object
  auth.RefreshTokenBody:
    properties:
      RefreshToken:
        type: string
    required:
    - RefreshToken
    type: object
  auth.SignupBody:
    properties:
      Email:
        type: string
      Password:
        maxLength: 16
        minLength: 6
        type: string
    required:
    - Email
    - Password
    type: object
  payments.registerPaymentBody:
    properties:
      Amount:
        type: string
    required:
    - Amount
    type: object
  users.ApplyReferralBody:
    properties:
      ReferralCode:
        type: string
    required:
    - ReferralCode
    type: object
info:
  contact:
    email: ashwin@flaq.club
    name: Ashwin Prasad
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://flaq.club/privacy-policy
  title: Flaq API
  version: "2.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Enter login details
        in: body
        name: LoginBody
        required: true
        schema:
          $ref: '#/definitions/auth.LoginBody'
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Add Data
        in: body
        name: SignupBody
        required: true
        schema:
          $ref: '#/definitions/auth.SignupBody'
      produces:
      - application/json
      responses: {}
      summary: User signup
      tags:
      - Auth
  /auth/token/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: RefreshTokenBody
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenBody'
      produces:
      - application/json
      responses: {}
      summary: Issue a new Access token
      tags:
      - Auth
  /payments:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Register a new UPI Payment
      tags:
      - Payments
  /payments/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Register Payment
        in: body
        name: registerPaymentBody
        required: true
        schema:
          $ref: '#/definitions/payments.registerPaymentBody'
      produces:
      - application/json
      responses: {}
      summary: Register a new UPI Payment
      tags:
      - Payments
  /users/apply-referral:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Add Referral Data
        in: body
        name: ApplyReferralBody
        required: true
        schema:
          $ref: '#/definitions/users.ApplyReferralBody'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Apply a referral code
      tags:
      - Users
  /users/profile:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get user profile
      tags:
      - Users
schemes:
- http
swagger: "2.0"
