basePath: /
definitions:
  auth.LoginBody:
    properties:
      DeviceToken:
        type: string
      Email:
        type: string
      Password:
        type: string
    required:
    - DeviceToken
    - Email
    - Password
    type: object
  auth.RefreshTokenBody:
    properties:
      RefreshToken:
        type: string
    required:
    - RefreshToken
    type: object
  auth.SignupBody:
    properties:
      Email:
        type: string
      Password:
        maxLength: 16
        minLength: 6
        type: string
    required:
    - Email
    - Password
    type: object
  campaigns.addQuizToCampaignBody:
    properties:
      CampaignId:
        type: string
      QuizTemplateId:
        type: string
    type: object
  campaigns.campaignBody:
    properties:
      AirdropPerUser:
        type: number
      Articles:
        items:
          $ref: '#/definitions/models.Article'
        type: array
      CurrentAirdrop:
        type: number
      Description:
        type: string
      FlaqReward:
        type: integer
      Image:
        type: string
      RequiredFlaq:
        type: integer
      TickerImgUrl:
        type: string
      TickerName:
        type: string
      Title:
        type: string
      TotalAirdrop:
        type: number
      YTVideoUrl:
        type: string
    required:
    - AirdropPerUser
    - CurrentAirdrop
    - FlaqReward
    - Image
    - RequiredFlaq
    - TickerImgUrl
    - TickerName
    - TotalAirdrop
    - YTVideoUrl
    type: object
  campaigns.campaignParticipationBody:
    properties:
      CampaignId:
        type: string
    type: object
  campaigns.quizParticipationBody:
    properties:
      Answers:
        items:
          type: integer
        type: array
      CampaignParticipationId:
        type: string
      QuizTemplateId:
        type: string
    required:
    - Answers
    - CampaignParticipationId
    - QuizTemplateId
    type: object
  models.Article:
    properties:
      IconUrl:
        type: string
      Title:
        type: string
      Url:
        type: string
    type: object
  models.Question:
    properties:
      AnswerIndex:
        type: integer
      Description:
        type: string
      Options:
        items:
          type: string
        type: array
      Question:
        type: string
    required:
    - AnswerIndex
    - Description
    - Options
    - Question
    type: object
  models.QuizTemplate:
    properties:
      Questions:
        items:
          $ref: '#/definitions/models.Question'
        type: array
      Title:
        type: string
      id:
        type: string
    required:
    - Questions
    - Title
    type: object
  payments.registerPaymentBody:
    properties:
      Amount:
        type: string
    required:
    - Amount
    type: object
  users.ApplyReferralBody:
    properties:
      ReferralCode:
        type: string
    required:
    - ReferralCode
    type: object
info:
  contact:
    email: ashwin@flaq.club
    name: Ashwin Prasad
    url: http://www.swagger.io/support
  description: This is a sample server server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://flaq.club/privacy-policy
  title: Flaq API
  version: "2.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Enter login details
        in: body
        name: LoginBody
        required: true
        schema:
          $ref: '#/definitions/auth.LoginBody'
      produces:
      - application/json
      responses: {}
      summary: User login
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Add Data
        in: body
        name: SignupBody
        required: true
        schema:
          $ref: '#/definitions/auth.SignupBody'
      produces:
      - application/json
      responses: {}
      summary: User signup
      tags:
      - Auth
  /auth/token/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: RefreshTokenBody
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenBody'
      produces:
      - application/json
      responses: {}
      summary: Issue a new Access token
      tags:
      - Auth
  /campaign/:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      responses: {}
      summary: Get all campaigns
      tags:
      - Campaigns
  /campaign/{id}/quiz:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Campaign ID
        in: path
        name: id
        required: true
        type: string
      responses: {}
      summary: Get all campaigns
      tags:
      - Campaigns
  /campaign/a:
    post:
      consumes:
      - application/json
      parameters:
      - description: Campaign Details
        in: body
        name: campaignBody
        required: true
        schema:
          $ref: '#/definitions/campaigns.campaignBody'
      responses: {}
      summary: Create a campaign
      tags:
      - Campaign Admin
  /campaign/a/quiz/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: Quiz and Campaign Details
        in: body
        name: addQuizToCampaignBody
        required: true
        schema:
          $ref: '#/definitions/campaigns.addQuizToCampaignBody'
      responses: {}
      summary: Create a quiz template [FOR ADMIN]
      tags:
      - Campaign Admin
  /campaign/a/quiz/template:
    post:
      consumes:
      - application/json
      parameters:
      - description: Campaign Details
        in: body
        name: models.QuizTemplate
        required: true
        schema:
          $ref: '#/definitions/models.QuizTemplate'
      responses: {}
      summary: Create a quiz template
      tags:
      - Campaign Admin
  /campaign/conversion:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      responses: {}
      summary: Get all conversions
      tags:
      - Conversion
  /campaign/participate:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Campaign ID
        in: body
        name: campaignParticipationBody
        required: true
        schema:
          $ref: '#/definitions/campaigns.campaignParticipationBody'
      responses: {}
      summary: Create a campaign
      tags:
      - Campaigns
  /campaign/quiz/evaluate:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Quiz and Campaign Details
        in: body
        name: quizParticipationBody
        required: true
        schema:
          $ref: '#/definitions/campaigns.quizParticipationBody'
      responses: {}
      summary: Evaluate a quiz submission
      tags:
      - Campaigns
  /payments:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Register a new UPI Payment
      tags:
      - Payments
  /payments/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Register Payment
        in: body
        name: registerPaymentBody
        required: true
        schema:
          $ref: '#/definitions/payments.registerPaymentBody'
      produces:
      - application/json
      responses: {}
      summary: Register a new UPI Payment
      tags:
      - Payments
  /rewards:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get all rewards for a user
      tags:
      - Rewards
  /users/apply-referral:
    post:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Add Referral Data
        in: body
        name: ApplyReferralBody
        required: true
        schema:
          $ref: '#/definitions/users.ApplyReferralBody'
      responses: {}
      summary: Apply a referral code
      tags:
      - Users
  /users/profile:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get user profile
      tags:
      - Users
schemes:
- https
- http
swagger: "2.0"
